### ISSUE TITLE
Character entity reference

### ISSUE THREAD

**Issue by jim-rosales** [benvanburen/prj-rev-bwfs-dasmoto#1]
The ampersand symbol `&` is a reserved character in HTML which is why it is currently being highlighted in red by GitHub as seen below. It is a reserved character since it is used to add other characters via an [entity reference](https://developer.mozilla.org/en-US/docs/Glossary/Entity). 

Considering this the correct way to add the ampersand symbol, in this case, is to replace `&` with `&amp;`

https://github.com/benvanburen/prj-rev-bwfs-dasmoto/blob/9430fcf893d0b05ac7fbd2ac923a7ba763ff90fe/Dasmoto/index.html#L10

**Comment by benvanburen** [comment]
Got it, thanks Jim!
