### ISSUE TITLE
Font tag use

### ISSUE THREAD

**Issue by jim-rosales** [benvanburen/prj-rev-bwfs-dasmoto#4]
It was a great idea to use the font tag but unfortunately, it is deprecated and no [longer supported in HTML5.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font)

Instead, you can use the `span` tag to group your text that you want to apply a particular style to.

For example:
```HTML
<p>
Imported paint from Finland. Over 256 colors available in-store, varying in quantity (1 oz. to 8 oz.). Clean Finnish paint microbinds to canvas, increasing the finish and longevity of any artwork. <span class="bluebold">Starting at $5.00 / tube.</span>
</p>
```

https://github.com/benvanburen/prj-rev-bwfs-dasmoto/blob/9430fcf893d0b05ac7fbd2ac923a7ba763ff90fe/Dasmoto/index.html#L32

**Comment by benvanburen** [comment]
It's been awhile since I've written html code. I will need to brush up on my deprecations.
